# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'Baseball_Players.png','loading.png','ball_shadow.png','ball.png','ENCR10B.TTF','SNES-Human_Baseball_JPN-Saitama.png','start_button.png','white_background.png'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
]

